#!/usr/bin/env python

import os
import sys

from bs4 import BeautifulSoup

not_food = """

alcohol
bill, check
boiling point
boil
bone
bottle
brandy
boned
cheese
chill
"""

def no_parentheticals(s):
  return s.partition('(')[0] if '(' in s else s

if __name__ == '__main__':

  wordlist_path = sys.argv[1]
  print >>sys.stderr, 'opening words at', wordlist_path

  if not os.path.exists(wordlist_path):
  	print >>sys.stderr, 'No wordlist found at', wordlist_path
  	sys.exit(-1)

  with open(wordlist_path) as words:
    html = words.read().decode('utf-8')
    soup = BeautifulSoup(html, from_encoding='utf-8')
    terms = []

    def add_term(term):
      term = term.strip()
      term = no_parentheticals(term)
      terms.append(term)

    for tr in soup.find_all('tr'):
      cells = tr.find_all('td')
      if 4 == len(cells):
        cell = cells[0]
        terms = cell.string.split(',')
        map(add_term, terms)

    for term in terms:
    	print term
