#!/usr/bin/env python

import os
import sys

from bs4 import BeautifulSoup

# terms present in cooking term list which should be excluded from lyric search.
not_food = """
add
alcohol
bill
brush
coat
gradually
heat
check
boiling point
boil
bone
kitchen tissue
light
bottle
brandy
boned
cheese
chill
turn
turn off
""".split()

not_food = [term.strip() for term in not_food]

print >>sys.stderr, not_food

def no_parentheticals(s):
  return s.partition('(')[0] if '(' in s else s

if __name__ == '__main__':

  wordlist_path = sys.argv[1]
  print >>sys.stderr, 'opening words at', wordlist_path

  if not os.path.exists(wordlist_path):
  	print >>sys.stderr, 'No wordlist found at', wordlist_path
  	sys.exit(-1)

  with open(wordlist_path) as words:
    html = words.read().decode('utf-8')
    soup = BeautifulSoup(html, from_encoding='utf-8')
    terms = []

    def add_term(term):
      term = term.strip()
      term = no_parentheticals(term)
      if term not in not_food:
        terms.append(term)

    for tr in soup.find_all('tr'):
      cells = tr.find_all('td')
      if 4 == len(cells):
        cell = cells[0]
        for term in  cell.string.split(','):
        	add_term(term)

    for term in terms:
    	print term.encode('utf-8')
